builds:
  - main: ./cmd/gotmpl
    binary: gotmpl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
checksum:
  name_template: 'gotmpl-checksums.txt'
archives:
  - name_template: "gotmpl-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
changelog:
  sort: asc
